name: saurc
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  image_picker: ^1.2.1
  location: ^8.0.1
  shared_preferences: ^2.5.4
  url_launcher: ^6.3.2
  google_fonts: ^8.0.2
  firebase_core: ^3.11.0
  firebase_auth: ^5.5.0
  cloud_firestore: ^5.6.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

# ESTA ES LA SECCIÓN QUE RECUPERA TUS ICONOS Y RECURSOS
flutter:
  uses-material-design: true

  # Si tienes imágenes para el Splash, asegúrate de que estén declaradas aquí
  # assets:
  #   - assets/images/